import json

sub_country_regions = {
    "GB-BKM": "England",
    "GB-CAM": "England",
    "GB-CMA": "England",
    "GB-DBY": "England",
    "GB-DEV": "England",
    "GB-DOR": "England",
    "GB-ESX": "England",
    "GB-ESS": "England",
    "GB-GLS": "England",
    "GB-HAM": "England",
    "GB-HRT": "England",
    "GB-KEN": "England",
    "GB-LAN": "England",
    "GB-LEC": "England",
    "GB-LIN": "England",
    "GB-NFK": "England",
    "GB-NYK": "England",
    "GB-NTH": "England",
    "GB-NTT": "England",
    "GB-OXF": "England",
    "GB-SOM": "England",
    "GB-STS": "England",
    "GB-SFK": "England",
    "GB-SRY": "England",
    "GB-WAR": "England",
    "GB-WSX": "England",
    "GB-WOR": "England",
    "GB-LND": "England",
    "GB-BDG": "England",
    "GB-BNE": "England",
    "GB-BEX": "England",
    "GB-BEN": "England",
    "GB-BRY": "England",
    "GB-CMD": "England",
    "GB-CRY": "England",
    "GB-EAL": "England",
    "GB-ENF": "England",
    "GB-GRE": "England",
    "GB-HCK": "England",
    "GB-HMF": "England",
    "GB-HRY": "England",
    "GB-HRW": "England",
    "GB-HAV": "England",
    "GB-HIL": "England",
    "GB-HNS": "England",
    "GB-ISL": "England",
    "GB-KEC": "England",
    "GB-KTT": "England",
    "GB-LBH": "England",
    "GB-LEW": "England",
    "GB-MRT": "England",
    "GB-NWM": "England",
    "GB-RDB": "England",
    "GB-RIC": "England",
    "GB-SWK": "England",
    "GB-STN": "England",
    "GB-TWH": "England",
    "GB-WFT": "England",
    "GB-WND": "England",
    "GB-WSM": "England",
    "GB-BNS": "England",
    "GB-BIR": "England",
    "GB-BOL": "England",
    "GB-BRD": "England",
    "GB-BUR": "England",
    "GB-CLD": "England",
    "GB-COV": "England",
    "GB-DNC": "England",
    "GB-DUD": "England",
    "GB-GAT": "England",
    "GB-KIR": "England",
    "GB-KWL": "England",
    "GB-LDS": "England",
    "GB-LIV": "England",
    "GB-MAN": "England",
    "GB-NET": "England",
    "GB-NTY": "England",
    "GB-OLD": "England",
    "GB-RCH": "England",
    "GB-ROT": "England",
    "GB-SHN": "England",
    "GB-SLF": "England",
    "GB-SAW": "England",
    "GB-SFT": "England",
    "GB-SHF": "England",
    "GB-SOL": "England",
    "GB-STY": "England",
    "GB-SKP": "England",
    "GB-SND": "England",
    "GB-TAM": "England",
    "GB-TRF": "England",
    "GB-WKF": "England",
    "GB-WLL": "England",
    "GB-WGN": "England",
    "GB-WRL": "England",
    "GB-WLV": "England",
    "GB-BAS": "England",
    "GB-BDF": "England",
    "GB-BBD": "England",
    "GB-BPL": "England",
    "GB-BCP": "England",
    "GB-BRC": "England",
    "GB-BNH": "England",
    "GB-BST": "England",
    "GB-CBF": "England",
    "GB-CHE": "England",
    "GB-CHW": "England",
    "GB-CON": "England",
    "GB-DAL": "England",
    "GB-DER": "England",
    "GB-DUR": "England",
    "GB-ERY": "England",
    "GB-HAL": "England",
    "GB-HPL": "England",
    "GB-HEF": "England",
    "GB-IOW": "England",
    "GB-IOS": "England",
    "GB-KHL": "England",
    "GB-LCE": "England",
    "GB-LUT": "England",
    "GB-MDW": "England",
    "GB-MDB": "England",
    "GB-MIK": "England",
    "GB-NEL": "England",
    "GB-NLN": "England",
    "GB-NSM": "England",
    "GB-NBL": "England",
    "GB-NGM": "England",
    "GB-PTE": "England",
    "GB-PLY": "England",
    "GB-POR": "England",
    "GB-RDG": "England",
    "GB-RCC": "England",
    "GB-RUT": "England",
    "GB-SHR": "England",
    "GB-SLG": "England",
    "GB-SGC": "England",
    "GB-STH": "England",
    "GB-SOS": "England",
    "GB-STT": "England",
    "GB-STE": "England",
    "GB-SWD": "England",
    "GB-TFW": "England",
    "GB-THR": "England",
    "GB-TOB": "England",
    "GB-WRT": "England",
    "GB-WBK": "England",
    "GB-WIL": "England",
    "GB-WNM": "England",
    "GB-WOK": "England",
    "GB-YOR": "England",
    "GB-ANN": "Ireland & Northern Ireland",
    "GB-AND": "Ireland & Northern Ireland",
    "GB-ABC": "Ireland & Northern Ireland",
    "GB-BFS": "Ireland & Northern Ireland",
    "GB-CCG": "Ireland & Northern Ireland",
    "GB-DRS": "Ireland & Northern Ireland",
    "GB-FMO": "Ireland & Northern Ireland",
    "GB-LBC": "Ireland & Northern Ireland",
    "GB-MEA": "Ireland & Northern Ireland",
    "GB-MUL": "Ireland & Northern Ireland",
    "GB-NMD": "Ireland & Northern Ireland",
    "GB-ABE": "Scotland",
    "GB-ABD": "Scotland",
    "GB-ANS": "Scotland",
    "GB-AGB": "Scotland",
    "GB-CLK": "Scotland",
    "GB-DGY": "Scotland",
    "GB-DND": "Scotland",
    "GB-EAY": "Scotland",
    "GB-EDU": "Scotland",
    "GB-ELN": "Scotland",
    "GB-ERW": "Scotland",
    "GB-EDH": "Scotland",
    "GB-ELS": "Scotland",
    "GB-FAL": "Scotland",
    "GB-FIF": "Scotland",
    "GB-GLG": "Scotland",
    "GB-HLD": "Scotland",
    "GB-IVC": "Scotland",
    "GB-MLN": "Scotland",
    "GB-MRY": "Scotland",
    "GB-NAY": "Scotland",
    "GB-NLK": "Scotland",
    "GB-ORK": "Scotland",
    "GB-PKN": "Scotland",
    "GB-RFW": "Scotland",
    "GB-SCB": "Scotland",
    "GB-ZET": "Scotland",
    "GB-SAY": "Scotland",
    "GB-SLK": "Scotland",
    "GB-STG": "Scotland",
    "GB-WDU": "Scotland",
    "GB-WLN": "Scotland",
    "GB-BGW": "Wales",
    "GB-BGE": "Wales",
    "GB-CAY": "Wales",
    "GB-CRF": "Wales",
    "GB-CMN": "Wales",
    "GB-CGN": "Wales",
    "GB-CWY": "Wales",
    "GB-DEN": "Wales",
    "GB-FLN": "Wales",
    "GB-GWN": "Wales",
    "GB-AGY": "Wales",
    "GB-MTY": "Wales",
    "GB-MON": "Wales",
    "GB-NTL": "Wales",
    "GB-NWP": "Wales",
    "GB-PEM": "Wales",
    "GB-POW": "Wales",
    "GB-RCT": "Wales",
    "GB-SWA": "Wales",
    "GB-TOF": "Wales",
    "GB-VGL": "Wales",
    "GB-WRX": "Wales",
    "US-AL": "U.S., Southern",
    "US-AK": "U.S., Northwestern",
    "US-AZ": "U.S., Western",
    "US-AR": "U.S., Southern",
    "US-CA": "U.S., Southwestern",
    "US-CO": "U.S., Western",
    "US-CT": "U.S., New England",
    "US-DE": "U.S., Mid-Atlantic",
    "US-FL": "U.S., Southern",
    "US-GA": "U.S., Southern",
    "US-HI": "U.S., Southwestern",
    "US-ID": "U.S., Northwestern",
    "US-IL": "U.S., Midwestern",
    "US-IN": "U.S., Midwestern",
    "US-IA": "U.S., Midwestern",
    "US-KS": "U.S., Midwestern",
    "US-KY": "U.S., Southern",
    "US-LA": "U.S., Southern",
    "US-ME": "U.S., New England",
    "US-MD": "U.S., Mid-Atlantic",
    "US-MA": "U.S., New England",
    "US-MI": "U.S., Midwestern",
    "US-MN": "U.S., Midwestern",
    "US-MS": "U.S., Southern",
    "US-MO": "U.S., Midwestern",
    "US-MT": "U.S., Northwestern",
    "US-NE": "U.S., Midwestern",
    "US-NV": "U.S., Southwestern",
    "US-NH": "U.S., New England",
    "US-NJ": "U.S., Mid-Atlantic",
    "US-NM": "U.S., Western",
    "US-NY": "U.S., Mid-Atlantic",
    "US-NC": "U.S., Southern",
    "US-ND": "U.S., Midwestern",
    "US-OH": "U.S., Midwestern",
    "US-OK": "U.S., Southwestern",
    "US-OR": "U.S., Northwestern",
    "US-PA": "U.S., Mid-Atlantic",
    "US-RI": "U.S., New England",
    "US-SC": "U.S., Southern",
    "US-SD": "U.S., Midwestern",
    "US-TN": "U.S., Southern",
    "US-TX": "U.S., Southwestern",
    "US-UT": "U.S., Southwestern",
    "US-VT": "U.S., New England",
    "US-VA": "U.S., Mid-Atlantic",
    "US-WA": "U.S., Northwestern",
    "US-WV": "U.S., Mid-Atlantic",
    "US-WI": "U.S., Midwestern",
    "US-WY": "U.S., Northwestern",
    "US-DC": "U.S., Mid-Atlantic"
}
countries = {
    "AF": "Asia, South",
    "AL": "Eastern Europe",
    "DZ": "Africa",
    "AS": "Pacific Islands",
    "AO": "Africa",
    "AI": "Caribbean",
    "AG": "Caribbean",
    "AR": "Latin America",
    "AW": "Caribbean",
    "AU": "Australia",
    "BS": "Caribbean",
    "BH": "Middle East",
    "BD": "Asia, South",
    "BB": "Caribbean",
    "BY": "Eastern Europe",
    "BZ": "Latin America",
    "BJ": "Africa",
    "BM": "Caribbean",
    "BT": "Asia, South",
    "BO": "Latin America",
    "BW": "Africa",
    "BV": "Antarctica",
    "BR": "Latin America",
    "BN": "Asia, Southeast",
    "BG": "Eastern Europe",
    "BF": "Africa",
    "BI": "Africa",
    "CV": "Africa",
    "KH": "Asia, Southeast",
    "CM": "Africa",
    "CA": "Canada",
    "KY": "Caribbean",
    "CF": "Africa",
    "TD": "Africa",
    "CL": "Latin America",
    "CN": "Asia, East",
    "CO": "Latin America",
    "KM": "Africa",
    "CG": "Africa",
    "CD": "Africa",
    "CK": "Pacific Islands",
    "CR": "Latin America",
    "CI": "Africa",
    "CU": "Caribbean",
    "CY": "Middle East",
    "CZ": "Eastern Europe",
    "DK": "Scandinavia",
    "DJ": "Africa",
    "DM": "Caribbean",
    "DO": "Caribbean",
    "EC": "Latin America",
    "EG": "Middle East",
    "SV": "Latin America",
    "GQ": "Africa",
    "ER": "Africa",
    "EE": "Eastern Europe",
    "SZ": "Africa",
    "ET": "Africa",
    "FK": "Latin America",
    "FJ": "Pacific Islands",
    "FI": "Scandinavia",
    "FR": "France",
    "GF": "Latin America",
    "PF": "Pacific Islands",
    "GA": "Africa",
    "GM": "Africa",
    "DE": "Germany",
    "GH": "Africa",
    "GR": "Greece",
    "GD": "Caribbean",
    "GP": "Caribbean",
    "GU": "Pacific Islands",
    "GT": "Latin America",
    "GN": "Africa",
    "GW": "Africa",
    "GY": "Latin America",
    "HT": "Caribbean",
    "HM": "Antarctica",
    "HN": "Latin America",
    "HU": "Eastern Europe",
    "IN": "Asia, South",
    "ID": "Asia, Southeast",
    "IR": "Middle East",
    "IQ": "Middle East",
    "IE": "Ireland & Northern Ireland",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Caribbean",
    "JP": "Asia, East",
    "JO": "Middle East",
    "KE": "Africa",
    "KI": "Pacific Islands",
    "KP": "Asia, East",
    "KR": "Asia, East",
    "KW": "Middle East",
    "LA": "Asia, Southeast",
    "LV": "Eastern Europe",
    "LB": "Middle East",
    "LS": "Africa",
    "LR": "Africa",
    "LY": "Africa",
    "LT": "Eastern Europe",
    "MG": "Africa",
    "MW": "Africa",
    "MY": "Asia, Southeast",
    "MV": "Asia, South",
    "ML": "Africa",
    "MH": "Pacific Islands",
    "MQ": "Caribbean",
    "MR": "Africa",
    "MU": "Africa",
    "YT": "Africa",
    "MX": "Mexico",
    "FM": "Pacific Islands",
    "MD": "Eastern Europe",
    "MN": "Asia, East",
    "MS": "Caribbean",
    "MA": "Africa",
    "MZ": "Africa",
    "MM": "Asia, Southeast",
    "NA": "Africa",
    "NR": "Pacific Islands",
    "NP": "Asia, South",
    "NC": "Pacific Islands",
    "NZ": "Pacific Islands",
    "NI": "Latin America",
    "NE": "Africa",
    "NG": "Africa",
    "NU": "Pacific Islands",
    "NF": "Pacific Islands",
    "MP": "Pacific Islands",
    "NO": "Scandinavia",
    "OM": "Middle East",
    "PK": "Asia, South",
    "PW": "Pacific Islands",
    "PS": "Middle East",
    "PA": "Latin America",
    "PY": "Latin America",
    "PE": "Latin America",
    "PH": "Asia, Southeast",
    "PN": "Pacific Islands",
    "PL": "Poland",
    "PR": "Caribbean",
    "QA": "Middle East",
    "RE": "Africa",
    "RO": "Eastern Europe",
    "RU": "Russia",
    "RW": "Africa",
    "BL": "Caribbean",
    "SH": "Africa",
    "KN": "Caribbean",
    "LC": "Caribbean",
    "MF": "Caribbean",
    "VC": "Caribbean",
    "WS": "Pacific Islands",
    "ST": "Africa",
    "SA": "Middle East",
    "SN": "Africa",
    "SC": "Africa",
    "SL": "Africa",
    "SG": "Asia, Southeast",
    "SK": "Eastern Europe",
    "SB": "Pacific Islands",
    "SO": "Africa",
    "ZA": "Africa",
    "ES": "Spain",
    "LK": "Asia, South",
    "SD": "Africa",
    "SR": "Latin America",
    "SE": "Scandinavia",
    "SY": "Middle East",
    "TW": "Asia, East",
    "TZ": "Africa",
    "TH": "Asia, Southeast",
    "TL": "Asia, Southeast",
    "TG": "Africa",
    "TK": "Pacific Islands",
    "TO": "Pacific Islands",
    "TT": "Caribbean",
    "TN": "Africa",
    "TR": "Middle East",
    "TC": "Caribbean",
    "TV": "Pacific Islands",
    "UG": "Africa",
    "UA": "Eastern Europe",
    "AE": "Middle East",
    "UY": "Latin America",
    "VU": "Pacific Islands",
    "VE": "Latin America",
    "VN": "Asia, Southeast",
    "VG": "Caribbean",
    "VI": "Caribbean",
    "WF": "Pacific Islands",
    "EH": "Africa",
    "YE": "Middle East",
    "ZM": "Africa",
    "ZW": "Africa"
}


with open('/Users/danom/mcitcode/cis550/sound-of-poetry/worldmap/world_fahey.json') as f:
    topo = json.load(f)

    for region in topo['features']:
        if 'region' in region.keys():
            print(f"Region already set to: {region['region']}")
            continue
        else:
            iso = region['properties']['iso_3166_2']
            if iso in sub_country_regions.keys():
                region['region'] = sub_country_regions[iso]
                print(f"Setting poet region to: {region['region']}")
            elif iso[0:2] in countries.keys():
                region['region'] = countries[iso[0:2]]
                print(f"Setting poet region to: {countries[iso[0:2]]}")
            else:
                region['region'] = iso[0:2]
                print(f"Setting region to: {iso[0:2]}")

with open('/Users/danom/mcitcode/cis550/sound-of-poetry/worldmap/world_poet_region.json', 'w') as w:
    json.dump(topo, w)