export enum HandwritingFontEnum {
    Annie = 'annie',
    Cedarville = 'cedarville',
    Dawning = 'dawning',
    Dokdo = 'dokdo',
    GiveGlory = 'giveGlory',
    Gloria = 'gloria',
    Homemade = 'homemade',
    JustMe = 'justMe',
    Kristi = 'kristi',
    Liu = 'liu',
    MrDafoe = 'mrDafoe',
    NanumBrush = 'nanumBrush',
    NanumPen = 'nanumPen',
    Nothing = 'nothing',
    OverRainbow = 'overRainbow',
    Reenie = 'reenie',
    RockSalt = 'rockSalt',
    Ruthie = 'ruthie',
    Sacramento = 'sacramento',
    Shadows = 'shadows',
    SueEllen = 'sueEllen',
    Swanky = 'swanky',
    TheGirl = 'theGirl',
    Waiting = 'waiting',
    Zeyada = 'zeyada'
}
