export enum TailwindHeightEnum {
    Auto = 'h-auto',
    OneHalf = 'h-1/2',
    OneThird = 'h-1/3',
    TwoThirds = 'h-2/3',
    OneFourths = 'h-1/4',
    TwoFourths = 'h-2/4',
    ThreeFourths = 'h-3/4',
    OneFifths = 'h-1/5',
    TwoFifths = 'h-2/5',
    ThreeFifths = 'h-3/5',
    FourFifths = 'h-4/5',
    OneSixths = 'h-1/6',
    TwoSixths = 'h-2/6',
    ThreeSixths = 'h-3/6',
    FourSixths = 'h-4/6',
    FiveSixths = 'h-5/6',
    Full = 'h-full',
    Screen90 = 'h-screen-90',
    Screen = 'h-screen'
}
